### ISSUE TITLE
Customer layout handles no longer work

### ISSUE THREAD

**Issue by kdckrs** [huguesalary/Magento-Varnish#12]
When using this module the login/logout links wouldn't show anymore so I went to debug.

Apparently the following handles that you can find in customer.xml are no longer working:
`<customer_logged_in>` and `<customer_logged_out>`

``` <customer_logged_out>
        <reference name="top.links">
            <action method="addLink" translate="label title" module="customer"><label>Log In</label><url helper="customer/getLoginUrl"/><title>Log In</title><prepare/><urlParams/><position>100</position></action>
        </reference>
    </customer_logged_out>
```

Doesn't add the login link, same goes for the logout link.

Would be great if you had any solution for this ;)

Thanks,
Kenny

**Comment by huguesalary** [comment]
Thanks for the report. I'll take a look as soon as I can.

**Comment by kdckrs** [comment]
Just looked into this a bit further, and it seems that the `<customer_logged_out>` and `<customer_logged_in>` handle IS working, only the addLink action method to add the Login/Logout link to the top menu is not working.

Hope this helps you out a bit further ;)
